### ISSUE TITLE
Library not seeing STL or zip files

### ISSUE THREAD

**Issue by bradleyallanpatterson** [manyfold3d/manyfold#1596]
I finally got VanDam (VD) working and after a lot of trial and error - it seems that my folder in the local folder is NOT seeing STL or OBJ files.  

My server:
Linux Mint, running latest docker and portainer in docker.

Steps used:
I can create a simple folder in the /libraries folder named test and rescan - FYI scanning icon never finishes even after 1 hour.
Refresh VD and you will see folder named test.  If I go into Linux and rename the folder and refresh the browser I see the name changes.
Now copy a zip, stl and obj to the test folder.
Rescan again .... wait ten minutes and refresh the browser.
No files are seen.

However, if I upload a zip file through the browser by clicking the Upload button the zip is uploaded and resides in the parent folder and NOT my libraries folder as specified in the yml.  Bottom line I see X number STLs in the zip file.

**Comment by Floppy** [comment]
I think this is probably due to unclear documentation on what folders are what, and probably some unclear naming on my part.

In the docker YAML, you can tell docker where to mount a volume that your files will be on, but that's just for the docker paths, VanDAM doesn't know anything about it yet. Then in VanDAM, you create a library and set a docker-relative path to the folder it should monitor.

It sounds to me like you've mounted the volume at `/libraries`, but it sounds like the Library you've made in VanDAM isn't looking at that path, it's looking at `/` perhaps? What's the path in the Library itself (you can see it at the bottom of the settings page).

If scan isn't finishing ever, click through to the tasks list that the scanning spinner should link to. You've probably got some jobs with errors in there, which can be deleted to free it up.

**Comment by bradleyallanpatterson** [comment]
Thanks for the quick response.  I watched the video from DB tech guy on YouTube.  Im at work now but will try and look at the mount when I’m home.  I also played around with vandam a few hours last night and found more possible bugs or features that might be a nice change but not sure.  Should I just enter them as bugs?  Should I add screenshots?  I’m a developer currently using python but interested in helping if possible.  Do you have instructions on building!the and ide(s) required??

**Comment by bradleyallanpatterson** [comment]
OK here is my snippet from my yml:
    volumes:
      - /mnt/12TB/vandam:/libraries

So if I create a folder called test at /mnt/12TB/vandam/libraries - I now have a path like this: /mnt/12TB/vandam/libraries/test

I upload stl and rescan - nothing appears.

**Comment by Floppy** [comment]
Right, so, when you create a Library in VanDAM, the path should be `/libraries/<your-library-folder-name>`; the part after the colon is the mapped path inside the docker container - the docs aren't very clear on that, sorry.

I'll attempt to make it clearer: when the container runs, the `/mnt/12TB/vandam` folder on your native machine is the SAME as the `/libraries` folder inside the container. So to VanDAM, `/libraries` is where it will be able to see your stuff. 

Let's say you have a `miniatures` folder inside `/mnt/12TB/vandam`; when you create a "Library" inside VanDAM, which you should have done at the first run, the path you need to give it is to a folder it understands, which will be `/libraries/miniatures` 

Then, if you create folders with models in inside that `miniatures` folder, the app will find them, and uploads should go to the same place.

Writing that out, it's hella confusing. I need to make this better. The whole volume mapping plus library path thing is too complex. At the end of the day, a VanDAM library can be any path, but because of docker, you need to add the path mapping from your local machine into the container, which adds a layer of confusion to the whole thing.

**Comment by Floppy** [comment]
(having to explain this is really helpful btw, it's really highlighted how confusing it is right now)

**Comment by bradleyallanpatterson** [comment]
Sorry but i have had family issues and unable to get to this for now.
I agree that the setting is weird and will try and think about this more.

**Comment by Floppy** [comment]
I've (hopefully) improved the documentation and UI a lot since this was filed; we can reopen it if necessary, but I think it can be resolved for now.
