### ISSUE TITLE
Touch input to 3D model view causes page scrolling

### ISSUE THREAD

**Issue by erbridge** [manyfold3d/manyfold#2379]
**Describe the bug**
On mobile (and possibly other touch input devices), dragging the 3D model around also causes the page to scroll.

**To Reproduce**
1. Go to https://try.manyfold.app/libraries/1/models/3
2. Drag up on the armadillo
3. See the model rotate and the page scroll down

**Expected behavior**
Only the 3D model should move when touch input starts on the 3D model view and only the page should move when touch input starts outside the 3D model view.

**Smartphone**
 - Device: Fairphone 5
 - OS: Android
 - Browser: Firefox
 - Version: 127.0.2

**Comment by Floppy** [comment]
Thanks - I think I've missed a preventDefault somewhere in all the input redirection shenanigans that happen with the background worker.

**Comment by Floppy** [comment]
Actually I wonder if this is because there are both https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events and https://developer.mozilla.org/en-US/docs/Web/API/Touch_events. I'm definitely handling pointer events and taking over the input, which I thought would do touch as well, but perhaps the specific touch events need to be silenced too while capture is happening.

**Comment by Floppy** [comment]
This might actually be as simple as setting `touch-action: none` on the canvas: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by Floppy** [comment]
Wow, that actually worked!
