### ISSUE TITLE
Include licensing information

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#461]
It would be good to be able to store license metadata perhaps? At the very least, commercial vs free.

NLNet Milestone 1.4

**Comment by ksuquix** [comment]
Seems like a good thing to just document how to use Tags to manage.  There are so many types of licenses it would be easier to let the user just tag things properly i'd think.

**Comment by silbe** [comment]
Not sure if you're already aware of it: [SPDX](https://spdx.dev/) has a nomenclature of licenses ([license identifiers](https://spdx.dev/ids/), also known as SPDX IDs). Would be great to have it as actual structured metadata that can be searched for rather than just free-form tags. Unfortunately many otherwise "open" licenses are incompatible with each other so when combining things the license is important. :tired_face: 

(FWIW I am not using VanDAM but I am interested in a non-profit alternative to printables / thingiverse and the ActivityPub federation discussed in #1389 looks like it might be a good fit).

**Comment by Floppy** [comment]
Thanks! I was thinking of basing the metadata around [Datapackage](https://dataprotocols.org/data-packages/), which uses [Open Definition](https://opendefinition.org/licenses/api/) license identifiers, but that's mainly because my background on this is open data focused, so I'll make sure I look at SPDX as well. Structured data is definitely the way forward, I agree.

There's more on this in https://github.com/Floppy/van_dam/issues/1040, which talks about defining a common package metadata format for 3d models, so you'll probably find that of interest too.

**Comment by Floppy** [comment]
Leaving myself a link here to the SPDX license list, which includes all sorts of things both data and source focused, so looks like a great standard to adopt: https://spdx.org/licenses/

I think the two are probably convergent anyway, certainly a brief skim looks that way.

**Comment by Floppy** [comment]
Well we both learned something! SPDX looks like the right approach; thanks for the pointer.

**Comment by Floppy** [comment]
The one thing SPDX doesn't have is an identifier for a generic commercial license (intentionally). https://scancode-licensedb.aboutcode.org/commercial-license.html is the best thing I've found after looking through a few discussion threads, so we can use `LicenseRef-scancode-commercial-license` for that case.
